run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-dirs:
    - frontend
    - build
